"""
Django settings for blockchain_gui project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-74sb3szximf&6+n(+=-2d9w64$)8j)%y#myeb+=b#j0sd3^^%l"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.34', 'localhost', '127.0.0.1','192.168.1.41', '192.168.232.185', '192.168.133.185']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "teacher_app",
    "blockchain_app",
    "crispy_forms",
    "crispy_bootstrap5",
]

# Cấu hình để sử dụng User model tùy chỉnh
AUTH_USER_MODEL = 'blockchain_app.User'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "blockchain_gui.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "blockchain_gui.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cấu hình Blockchain
BLOCKCHAIN_NODES = {
    'pdt': 'http://localhost:8000',
    'gv': 'http://localhost:8001',
    'sv': 'http://localhost:8002'
}

# Xác định node hiện tại dựa trên biến môi trường
NODE_TYPE = os.environ.get('NODE_TYPE', 'pdt')  # 'pdt', 'gv', hoặc 'sv'

# Cấu hình theo loại node
if NODE_TYPE == 'pdt':
    # Cấu hình cho node phòng đào tạo
    CAN_MINE_BLOCKS = True
    CAN_APPROVE_TRANSACTIONS = True
    CAN_SUBMIT_TRANSACTIONS = False
elif NODE_TYPE == 'gv':
    # Cấu hình cho node giảng viên
    CAN_MINE_BLOCKS = False
    CAN_APPROVE_TRANSACTIONS = False
    CAN_SUBMIT_TRANSACTIONS = True
else:  # 'sv'
    # Cấu hình cho node sinh viên
    CAN_MINE_BLOCKS = False
    CAN_APPROVE_TRANSACTIONS = False
    CAN_SUBMIT_TRANSACTIONS = False
