# Generated by Django 5.1.7 on 2025-03-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0002_transaction_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Nhân viên phòng đào tạo'), ('teacher', 'Giảng viên')], default='staff', max_length=10),
        ),
    ]
