# Generated by Django 5.1.7 on 2025-03-25 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approving_staff',
            field=models.ManyToManyField(blank=True, related_name='approving_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
