# Generated by Django 5.1.7 on 2025-03-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0004_transaction_approving_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('expired', 'Hết hạn')], default='pending', max_length=10),
        ),
    ]
