# Generated by Django 5.1.7 on 2025-03-26 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0007_transaction_approver_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='approver_signature',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='creator_signature',
        ),
    ]
